[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eleven"
version = "0.1.0"
authors = [
    { name = "Your Name" },
]
description = "Eleven AI Chat Project"
requires-python = ">=3.8"
dependencies = [
    "langchain-openai>=0.0.5",
    "langgraph>=0.0.10",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
]
