# Generated by Django 5.1.6 on 2025-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_eleven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleven',
            name='mood',
            field=models.CharField(choices=[('calm', 'Calm'), ('chill', 'Chill'), ('classy', 'Classy'), ('professional', 'Professional')], max_length=20),
        ),
    ]
